force-app/main/default/objects/Order/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Kustom Kreation Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pre-Orders</relationshipLabel>
    <relationshipName>Pre_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Location__c.field-meta.xml
<CustomField>
    <fullName>Order_Location__c</fullName>
    <label>Order Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Kustom Kreations Austin</fullName>
            </value>
            <value>
                <fullName>Kustom Kreations Las Vegas</fullName>
            </value>
            <value>
                <fullName>Kustom Kreations Los Angeles</fullName>
            </value>
            <value>
                <fullName>Kustom Kreations Miami</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KustomKreationsController.cls
public class KustomKreationsController {
private String sortOrder = 'OrderNumber';
public List<Order> getOrders(){
        List<Order> results = Database.query(
            'SELECT Customer_Name__r.name, Status, OrderNumber, Order_Location__c ' + 'FROM Order ' + 'ORDER By ' + sortOrder);
        return results;
    }

    public void sortbyOrderNumber(){
    this.sortOrder = 'OrderNumber';
}
    public void sortByLocationName(){
    this.sortOrder = 'Order_Location__c';
}
}