force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Kustom Kreation Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pre-Orders</relationshipLabel>
    <relationshipName>Pre_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Location__c.field-meta.xml
<CustomField>
    <fullName>Order_Location__c</fullName>
    <label>Order Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Kustom Kreations Austin</fullName>
            </value>
            <value>
                <fullName>Kustom Kreations Las Vegas</fullName>
            </value>
            <value>
                <fullName>Kustom Kreations Los Angeles</fullName>
            </value>
            <value>
                <fullName>Kustom Kreations Miami</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Wrapping_Choice__c.field-meta.xml
<CustomField>
    <fullName>Wrapping_Choice__c</fullName>
    <label>Wrapping Choice</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Curbside Deluxe</fullName>
            </value>
            <value>
                <fullName>Curbside Executive</fullName>
            </value>
            <value>
                <fullName>Curbside Standard</fullName>
            </value>
            <value>
                <fullName>In Store Deluxe</fullName>
            </value>
            <value>
                <fullName>In Store Executive</fullName>
            </value>
            <value>
                <fullName>In Store Standard</fullName>
            </value>
            <value>
                <fullName>Online Deluxe</fullName>
            </value>
            <value>
                <fullName>Online Executive</fullName>
            </value>
            <value>
                <fullName>Online Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KustomKreationsTesting.cls
@isTest
public class KustomKreationsTesting {
    @isTest static void testOrders(){
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Active__c = 'Yes';
        insert acc; 
        
        Contact con = new Contact(); 
        con.FirstName = 'Pam';
        con.Lastname = 'Williams';
        con.Phone = '222-545-3233';
        insert con; 
        
        
        Order one = new Order();
         one.Customer_Name__c = con.Id;
         one.EffectiveDate = Date.newInstance(2022, 7, 25);
         one.EndDate = System.today().addDays(10);
         one.Order_Location__c = 'Kustom Kreations Las Vegas';
         one.Wrapping_Choice__c = 'In Store Standard';
         one.Status = 'Submitted';
         one.AccountId = acc.Id;
        
         insert one;
        
        KustomKreationsController kkc = new KustomKreationsController();
       Test.startTest();
       List<Order> orderResult =  kkc.getOrders();
        
        system.debug(orderResult);
        kkc.sortByLocationName();
        kkc.sortbyOrderNumber();
        Test.stopTest();

    }
}